# Header
menu:
  首页: /
  所有文章: /archives
  关于: /2014/10/27/关于我/

# SubNav
subnav:
  github: "https://github.com/sunhao-java"
  weibo: "http://weibo.com/sunhaojava"
  #rss: "#"
  zhihu: "http://www.zhihu.com/people/crazy_coder"
  #douban: "http://www.douban.com/people/crazy_coder/"
  mail: "mailto:sunhao.java@gmail.com"
  #facebook: "https://www.facebook.com/sunhao.hava"
  #google: "https://plus.google.com/u/0/110606101600764499161"
  #twitter: "https://twitter.com/sunhao_java"
  #linkedin: "https://cn.linkedin.com/in/sunhaojava"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /img/coder.jpg

#你的头像url
avatar: /img/coder.jpg
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: sunhao
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  Github:
    url: https://github.com/sunhao-java
    icon: github.ico
  Git@OSC:
    url: https://git.oschina.net/sunhao-java
    icon: git@osc.gif
  我的开源中国:
    url: http://my.oschina.net/sunhaojava
    icon: oschina.png
  新浪微博:
    url: http://weibo.com/sunhaojava
    icon: sina.png

#是否开启“关于我”。
#是否开启“关于我”。
#不开启——
#aboutme: true
#开启——
aboutme: 1. 这就是现在的生活，沉浸在技术的海洋中，带着对技术的崇拜和敬畏，在人生的道路上小心翼翼的前进着！i believe can do if i tkink i can do！2. 善于创造机会的大脑+善于发现机会的眼睛+善于抓住机会的双手=成功
