# Header
menu:
  所有文章: /archives/
  Java: /tags/Java
  Linux: /tags/Linux
  数据库: /tags/database
  前端: /tags/frontend
  生活随笔: /tags/生活
  关于我: /about/

# Site favicon
favicon: /favicon.png

# Site logo
# logo: /avatar.png

# Enable Mathjax
mathjax: false

# Enable awesome-toc
awesome_toc: true

# Enable githubRepoWidget
github_repo_widget: true